#!/bin/bash

export PYTHONDONTWRITEBYTECODE=1

## initionaliztion variables
input_dir=None
output_dir=None
threads=6
T2=None
myelin=None
matrix=None
gradients=None
moment=None
all=TRUE

## input variables
for arg in "$@"
do
  case "$arg" in
  -input_dir)
    input_dir=$2
    shift;shift
  ;;

  -output_dir)
    output_dir=$2
    shift;shift
  ;;

  -T2)
    T2=TRUE
    shift
  ;;

  -myelin)
    myelin=TRUE
    shift
  ;;

  -matrix)
    matrix=TRUE
    shift
  ;;
 
  -gradients)
    gradients=TRUE
    shift
  ;;

  -moment)
    moment=TRUE
    shift
  ;;

  -all)
    all=TRUE
    shift
  ;;

  -threads)
    threads=$2
    shift;shift
  ;;

  esac
done

## checking variables
if [ ! -d $input_dir ];  then
	echo "#######################################################"
	echo ""
	echo "please enter your input data diractory path"
        echo ""
	echo "#######################################################"

	exit
fi

if [ ! -d $output_dir ];  then
        echo "#######################################################"
        echo ""
        echo "please enter your output data diractory path"
        echo ""
        echo "#######################################################"

        exit
fi

atlas_list=$(<$GANMAT/parcellations/atlas_list.txt)

## make sub list
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --make_sub_list=TRUE
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --make_dir=TRUE

sub_list=$(<$output_dir/sub_list.txt)

## making freesurfer space T1w
source $GANMAT/functions/preprocessing.sh $GANMAT $input_dir $output_dir $threads fs

## T1 registrate to MNI152_0.8
source $GANMAT/functions/preprocessing.sh $GANMAT $input_dir $output_dir $threads t1

## making T2 images
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --resize=TRUE
python $GANMAT/functions/model/main.py --pipeline_dir=$GANMAT --input_dir=$input_dir --batch_size=1 --output_dir=$output_dir
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --resize_inv=TRUE

##### T2
source $GANMAT/functions/preprocessing.sh $GANMAT $input_dir $output_dir $threads t2

if [ $T2 == TRUE ]; then
	exit
fi
######################################################################################

##### myelin
source $GANMAT/functions/preprocessing.sh $GANMAT $input_dir $output_dir $threads myelin

if [ $myelin == TRUE ]; then
	exit
fi
#######################################################################################

# make microstructural intensity
source $GANMAT/functions/preprocessing.sh $GANMAT $input_dir $output_dir $threads MPC

##### MPC matrix
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --matrix=TRUE

if [ $matrix == TRUE ]; then
	exit
fi
#######################################################################################

##### gradients
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --gradients=TRUE

if [ $gradients == TRUE ]; then
	exit
fi
#######################################################################################

##### moments
python $GANMAT/functions/preprocessing.py --GANMAT=$GANMAT --input_dir=$input_dir --output_dir=$output_dir --moment=TRUE

if [ $moment == TRUE ]; then
	exit
fi
#######################################################################################
